language: node_js
os: linux
dist: xenial
node_js:
- "10"

jobs:
  include:          
    - stage: Lint
      script:
        - npm run lint
    - stage: Test
      script:
        - npm run test
    - stage: Release application
      before_script:
        - npm install -g sass
      script:
        - cp .env.testnet .env && npm run build
        - tar cvzf tomox-sdk-ui.$TRAVIS_TAG.testnet.tar.gz ./build
        - cp .env.mainnet .env && npm run build
        - tar cvzf tomox-sdk-ui.$TRAVIS_TAG.tar.gz ./build
      deploy:
        provider: releases
        token: $GH_TOKEN
        file:
          - tomox-sdk-ui.$TRAVIS_TAG.tar.gz
          - tomox-sdk-ui.$TRAVIS_TAG.testnet.tar.gz
        overwrite: true
        on:
          tags: true

stages:
  - name: Lint
  - name: Test
  - name: Release application
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = tomochain/tomox-sdk-ui
